### ISSUE TITLE
Rename "return" to "finish"

### ISSUE THREAD

**Issue by axic** [ewasm/design#103]
The problem is that `return` is usually a keyword in languages and therefore in most of them when importing the `return` EEI method the user has to use an alternative name.

The benefit of the change is that this won't be a problem anymore.

**Comment by axic** [comment]
I think this kind of depends on #72, because if `finish` isn't stopping execution then it is a bit misleading.

**Comment by hugo-dc** [comment]
I think it would be idea to rename the `return` eei method. Right now each one of the EEI method has a similar name to the opcodes, I think it would be good to rename it in a way that still is evident that the method has the behavior of the RETURN opcode, at first I was thinking as something like `returnData`, but as @axic pointed out, that name can be confusing since we already have some methods with similar name such as: `getReturnDataSize` and `returnDataCopy`, another suggestion would be: `setReturnData`

**Comment by poemm** [comment]
`finish` works. Some more options: `terminate`, `halt`, `exit`, `exitCall`, `returnAndExit`, `returnFromCall`. I prefer `returnFromCall` since it refers to the `call*` EEI procedures. This way it won't be confused with the `return` Wasm opcode or language keyword.

**Comment by axic** [comment]
Decision today was to move on with `finish` and merge this irrelevant of #87 since `return` isn't a better name if it doesn't terminate.
