### ISSUE TITLE
WebAssembly (may) switch from AST to being a stack machine

### ISSUE THREAD

**Issue by axic** [ewasm/design#31]
See the conversation at Binaryen: https://github.com/WebAssembly/binaryen/issues/663

We need to investigate how does this affects eWASM.

**Comment by wanderer** [comment]
the biggest concerns would be 
* changes in the s-expression format (since evm2wasm is based on s-expr)
* level 1 compression. Being able to dedupe the AST for compression like [JSzap](https://www.usenix.org/conference/webapps-10/jszap-compressing-javascript-code) is really nice, would there be an equivant here?
* metering injection should not be affected (besides any possible changes to the AST) since control flow won't change much here

**Comment by kripken** [comment]
Just an fyi, more detailed discussion is on the wasm design repo at https://github.com/WebAssembly/design/issues/736.

**Comment by d-cook** [comment]
I believe that switching to a stack machine is short-sighted and a big mistake:

The AST format could open up new possibilities for software, some of which are observable in Lispy languages like Scheme (I won't list them here). Instead, we're looking at locking the software world back into this 1960's model for another 50 years out of a misguided concern for optimization over power.

It's like foregoing the arch because it's more work to craft, and instead coming up with a REALLY efficient way to fit square blocks together. Congratulations, we can build better pyramids, but will never grasp the concept of a cathedral.

To really grasp my point, I BEG you all to watch the following two videos in full and think hard about what Alan Kay & Douglass Crockford have to say about new ideas, building complex structures, and leaving something better for the next generation:

https://youtu.be/oKg1hTOQXoY

https://www.youtube.com/watch?v=PSGEjv3Tqo0

As Alan Kay states, what is simpler: something that's easier to process, but for which the software written on top of it is massive; or one that takes a bit more overhead, but allows for powerful new ways to model software and reduce complexity?

I believe that an AST model is a major start in inventing "the arch" that's been missing in software, and with something that will proliferate the whole web ... how short-sighted it would be to give that up in favor of "optimizing" the old thing.

Imagine if instead of JavaScript, the language of the web had been Java? Lambdas would not be mainstream; new ways of doing OOP would not be thought of; and all the amazing libraries that have been written because of the ad-hoc object modeling that JavaScript offers. Probably one of the messiest and inefficient languages ever written, yet one of the most powerful ever given. C'mon, let's do it a step more by making it binary, homoiconic, and self-modifying.

Thanks.
