### ISSUE TITLE
getBlockTimestamp need to return an i64?

### ISSUE THREAD

**Issue by wanderer** [ewasm/design#49]

**Comment by wanderer** [comment]
also does getBlockHash need an i64?

**Comment by axic** [comment]
Proposal:
- keep `getBlockTimestamp` as returning 64 bit as that is the standard way of handling POSIX timestamps
- keep`getBlockHash` to take a 64 bit argument

An unsigned 32 bit value has a range from 0 to 4294967295. Hypothetically if a block would be produced every second, it would take ~136 years to run out of the block number range. Or 34 years if a block is produced every 250 ms.

Based on this calculation it doesn't seem useful to keep it at 64 bit.

Some reasoning is:
- [EVMC](https://github.com/ethereum/evmc) uses that to represent block number
- values apart from pointers and length of the pointed memory is almost exclusively 64 bit in the EEI

**Comment by jakelang** [comment]
I think it makes sense to keep the timestamp type as 64 bit, simply to keep it similar to `time_t` on a 64-bit arch and because there is no perceivable downside to keeping it that way.

It would also be much cleaner to stay in line with EVMC's representation as @axic has said, keeping the blocknumber as an i64.

**Comment by axic** [comment]
Agreed today that we keep both of these at 64bit.
