### ISSUE TITLE
should `unreachable` not  OOG and just revert the state?

### ISSUE THREAD

**Issue by wanderer** [ewasm/design#60]
Currently unreachable works just like an invalid opcode in EVM1, but it could provide a nicer way of handling reverts

**Comment by axic** [comment]
I think this is a good idea, but would suggest to keep the behaviour as is. Since this issue was opened, the EVM introduced the `REVERT` opcode.

Reasoning: `revert()` will mark the transaction as reverted and will not charge all the gas. `unreachable` then still remains as a second option to abort a transaction.

These two kinds of aborts are utilised by static analysis tools on Ethereum, where `revert` is usually corresponds to a pre-condition and `unreachable` corresponds to an assertion.

**Comment by chfast** [comment]
I don't think there is any reason to additionally consume remaining gas in case of any kind of failure. If we accept this fact, the only matter that is left is how to report different kinds of failures.

**Comment by axic** [comment]
Decision: document that `unreachable` results in OOG.

**Comment by chfast** [comment]
I think it would be more correct to document that a _trap_ results in OOG.
